# Site settings
title: "Blog Teonácio"
email: brunoteonacio@gmail.com
description: "Blog relacionado a publicações e outras participações envolvendo a mim (Bruno Teonácio)."
baseurl: ""
url: ""
title_description: "Blog de Bruno Teonácio dos Santos.<br><br>Aqui publicarei alguns projetos e outros eventos que me envolvam.<br>Sintam-se a vontade para comentar as minhas publicações (adoro feedback).<br>Caso queiram entrar em contato comigo, as minhas redes sociais estão aparecendo abaixo.<br><br>Tenha um ótimo dia!<br><br><br>Email para contato: brunoteonacio@gmail.com<br><br>Nota: Qualquer algoritmo (código ou lógica) publicado aqui é de domínio público, mas em caso de cópia, gostaria de ser citado como autor - :)."
#title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
title_image: "https://avatars1.githubusercontent.com/u/14273246?s=400&v=4"
google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
github_repository: https://github.com/teonacio
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
#twitter_username: _jacobtomlinson
github_username: teonacio
#instagram_username: 
#reddit_username: 
linkedin_link: https://www.linkedin.com/in/bruno-teon%C3%A1cio-a44126124
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
#stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
#xing_link:
facebook_link: https://pt-br.facebook.com/bruno.teonacio

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Disqus Comments
disqus_shortname: teonacio-github-io

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
